# Generated by Django 3.2.12 on 2022-07-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220706_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_plan_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
