# Generated by Django 3.2.12 on 2022-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220716_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_free_trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
