# Generated by Django 3.2.12 on 2022-04-02 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('dateTimeStamp', models.DateTimeField(blank=True, null=True)),
                ('commodity', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cny',
            name='predicted_price',
        ),
        migrations.RemoveField(
            model_name='euro',
            name='predicted_price',
        ),
        migrations.RemoveField(
            model_name='gbp',
            name='predicted_price',
        ),
        migrations.RemoveField(
            model_name='gold',
            name='predicted_price',
        ),
        migrations.RemoveField(
            model_name='jpy',
            name='predicted_price',
        ),
    ]
