# Generated by Django 3.2.12 on 2022-04-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220402_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cny',
            name='is_data_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='euro',
            name='is_data_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gbp',
            name='is_data_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gold',
            name='is_data_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jpy',
            name='is_data_processed',
            field=models.BooleanField(default=False),
        ),
    ]
