# Generated by Django 3.2.12 on 2022-03-15 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, verbose_name='Product Name')),
                ('price', models.IntegerField(default=0, verbose_name='Product Price')),
                ('billingPeriod', models.CharField(max_length=70, verbose_name='Billing Period')),
                ('stripeProductId', models.CharField(max_length=256, verbose_name='Stripe Product Id')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('stripeCustomerId', models.CharField(max_length=255, verbose_name='Stripe Customer Id')),
                ('stripeSubscriptionId', models.CharField(max_length=255, verbose_name='Stripe Subscription Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
