# Generated by Django 3.2.12 on 2022-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20220316_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='subscriptionEndDate',
            field=models.CharField(max_length=50, verbose_name='Subscription End Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='subscriptionEndDate',
            field=models.CharField(max_length=50, verbose_name='Subscription End Date'),
        ),
    ]
